# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BodyReg.ui'
#
# Created: Sun Apr 23 00:39:35 2017
#      by:Paul Cyryl
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(779, 593)
        Dialog.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 170, 0, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));"))
        self.TitleFrame = QtGui.QFrame(Dialog)
        self.TitleFrame.setGeometry(QtCore.QRect(0, 0, 781, 80))
        self.TitleFrame.setObjectName(_fromUtf8("TitleFrame"))
        self.Title = QtGui.QVBoxLayout(self.TitleFrame)
        self.Title.setObjectName(_fromUtf8("Title"))
        self.Title_2 = QtGui.QLabel(self.TitleFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wide Latin"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Title_2.setFont(font)
        self.Title_2.setStyleSheet(_fromUtf8("background-color: rgb(0, 170, 0);\n"
"border :none;"))
        self.Title_2.setObjectName(_fromUtf8("Title_2"))
        self.Title.addWidget(self.Title_2)
        self.Middleframe = QtGui.QFrame(Dialog)
        self.Middleframe.setGeometry(QtCore.QRect(0, 90, 771, 341))
        self.Middleframe.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Middleframe.setFrameShadow(QtGui.QFrame.Raised)
        self.Middleframe.setObjectName(_fromUtf8("Middleframe"))
        self.DetailsFrame = QtGui.QFrame(self.Middleframe)
        self.DetailsFrame.setGeometry(QtCore.QRect(0, -10, 381, 351))
        self.DetailsFrame.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.DetailsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.DetailsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.DetailsFrame.setObjectName(_fromUtf8("DetailsFrame"))
        self.Name = QtGui.QLabel(self.DetailsFrame)
        self.Name.setGeometry(QtCore.QRect(10, 30, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Demi"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Name.setFont(font)
        self.Name.setObjectName(_fromUtf8("Name"))
        self.Id = QtGui.QLabel(self.DetailsFrame)
        self.Id.setGeometry(QtCore.QRect(20, 90, 131, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Demi Cond"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Id.setFont(font)
        self.Id.setObjectName(_fromUtf8("Id"))
        self.KinName = QtGui.QLabel(self.DetailsFrame)
        self.KinName.setGeometry(QtCore.QRect(20, 150, 131, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Demi Cond"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.KinName.setFont(font)
        self.KinName.setObjectName(_fromUtf8("KinName"))
        self.KinNumber = QtGui.QLabel(self.DetailsFrame)
        self.KinNumber.setGeometry(QtCore.QRect(20, 210, 131, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Demi Cond"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.KinNumber.setFont(font)
        self.KinNumber.setObjectName(_fromUtf8("KinNumber"))
        self.Date = QtGui.QLabel(self.DetailsFrame)
        self.Date.setGeometry(QtCore.QRect(20, 270, 131, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Demi Cond"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Date.setFont(font)
        self.Date.setObjectName(_fromUtf8("Date"))
        self.KinNameEntry = QtGui.QLineEdit(self.DetailsFrame)
        self.KinNameEntry.setGeometry(QtCore.QRect(160, 150, 211, 20))
        self.KinNameEntry.setObjectName(_fromUtf8("KinNameEntry"))
        self.KinNumberEntry = QtGui.QLineEdit(self.DetailsFrame)
        self.KinNumberEntry.setGeometry(QtCore.QRect(160, 210, 211, 20))
        self.KinNumberEntry.setObjectName(_fromUtf8("KinNumberEntry"))
        self.IdEntry = QtGui.QLineEdit(self.DetailsFrame)
        self.IdEntry.setGeometry(QtCore.QRect(160, 90, 211, 20))
        self.IdEntry.setObjectName(_fromUtf8("IdEntry"))
        self.NameEntry = QtGui.QLineEdit(self.DetailsFrame)
        self.NameEntry.setGeometry(QtCore.QRect(160, 30, 211, 20))
        self.NameEntry.setObjectName(_fromUtf8("NameEntry"))
        self.DateEntry = QtGui.QLineEdit(self.DetailsFrame)
        self.DateEntry.setGeometry(QtCore.QRect(160, 270, 211, 20))
        self.DateEntry.setObjectName(_fromUtf8("DateEntry"))
        self.servicesFrame = QtGui.QFrame(self.Middleframe)
        self.servicesFrame.setGeometry(QtCore.QRect(390, 0, 391, 341))
        self.servicesFrame.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.servicesFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.servicesFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.servicesFrame.setObjectName(_fromUtf8("servicesFrame"))
        self.ServicesFrame = QtGui.QLabel(self.servicesFrame)
        self.ServicesFrame.setGeometry(QtCore.QRect(95, 10, 151, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SketchFlow Print"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ServicesFrame.setFont(font)
        self.ServicesFrame.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"background-color: rgb(0, 255, 255);\n"
"border:none;"))
        self.ServicesFrame.setObjectName(_fromUtf8("ServicesFrame"))
        self.BodyWashing = QtGui.QCheckBox(self.servicesFrame)
        self.BodyWashing.setGeometry(QtCore.QRect(20, 50, 141, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Britannic Bold"))
        font.setPointSize(12)
        font.setItalic(True)
        self.BodyWashing.setFont(font)
        self.BodyWashing.setObjectName(_fromUtf8("BodyWashing"))
        self.Embalming = QtGui.QCheckBox(self.servicesFrame)
        self.Embalming.setGeometry(QtCore.QRect(20, 100, 141, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Britannic Bold"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Embalming.setFont(font)
        self.Embalming.setObjectName(_fromUtf8("Embalming"))
        self.VIP = QtGui.QCheckBox(self.servicesFrame)
        self.VIP.setGeometry(QtCore.QRect(20, 150, 141, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Britannic Bold"))
        font.setPointSize(12)
        font.setItalic(True)
        self.VIP.setFont(font)
        self.VIP.setObjectName(_fromUtf8("VIP"))
        self.Coffin = QtGui.QCheckBox(self.servicesFrame)
        self.Coffin.setGeometry(QtCore.QRect(20, 210, 141, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Britannic Bold"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Coffin.setFont(font)
        self.Coffin.setObjectName(_fromUtf8("Coffin"))
        self.Hearse = QtGui.QCheckBox(self.servicesFrame)
        self.Hearse.setGeometry(QtCore.QRect(20, 270, 141, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Britannic Bold"))
        font.setPointSize(12)
        font.setItalic(True)
        self.Hearse.setFont(font)
        self.Hearse.setObjectName(_fromUtf8("Hearse"))
        self.FlowerServices = QtGui.QCheckBox(self.servicesFrame)
        self.FlowerServices.setGeometry(QtCore.QRect(190, 50, 151, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Britannic Bold"))
        font.setPointSize(12)
        font.setItalic(True)
        self.FlowerServices.setFont(font)
        self.FlowerServices.setObjectName(_fromUtf8("FlowerServices"))
        self.DeathCertificate = QtGui.QCheckBox(self.servicesFrame)
        self.DeathCertificate.setGeometry(QtCore.QRect(190, 210, 151, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Britannic Bold"))
        font.setPointSize(12)
        font.setItalic(True)
        self.DeathCertificate.setFont(font)
        self.DeathCertificate.setObjectName(_fromUtf8("DeathCertificate"))
        self.PostMortem = QtGui.QCheckBox(self.servicesFrame)
        self.PostMortem.setGeometry(QtCore.QRect(190, 100, 151, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Britannic Bold"))
        font.setPointSize(12)
        font.setItalic(True)
        self.PostMortem.setFont(font)
        self.PostMortem.setObjectName(_fromUtf8("PostMortem"))
        self.TextServices = QtGui.QCheckBox(self.servicesFrame)
        self.TextServices.setGeometry(QtCore.QRect(190, 150, 151, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Britannic Bold"))
        font.setPointSize(12)
        font.setItalic(True)
        self.TextServices.setFont(font)
        self.TextServices.setObjectName(_fromUtf8("TextServices"))
        self.OtherServices = QtGui.QCheckBox(self.servicesFrame)
        self.OtherServices.setGeometry(QtCore.QRect(190, 270, 151, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Britannic Bold"))
        font.setPointSize(12)
        font.setItalic(True)
        self.OtherServices.setFont(font)
        self.OtherServices.setObjectName(_fromUtf8("OtherServices"))
        self.SubmitButton = QtGui.QPushButton(self.servicesFrame)
        self.SubmitButton.setGeometry(QtCore.QRect(134, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Script MT Bold"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.SubmitButton.setFont(font)
        self.SubmitButton.setStyleSheet(_fromUtf8("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(0, 85, 255, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.345 rgba(235, 219, 102, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.52 rgba(209, 190, 76, 255), stop:0.57 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.88 rgba(187, 156, 51, 255), stop:0.935 rgba(137, 108, 26, 255), stop:1 rgba(35, 40, 3, 255));\n"
"border:none;"))
        self.SubmitButton.setObjectName(_fromUtf8("SubmitButton"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.Title_2.setText(_translate("Dialog", "                                 BODY REGISTRATION", None))
        self.Name.setText(_translate("Dialog", "              Name", None))
        self.Id.setText(_translate("Dialog", "            ID Number", None))
        self.KinName.setText(_translate("Dialog", "Next Of Kin Name", None))
        self.KinNumber.setText(_translate("Dialog", "Kin Phone Number", None))
        self.Date.setText(_translate("Dialog", "                      Date", None))
        self.ServicesFrame.setText(_translate("Dialog", "   Services", None))
        self.BodyWashing.setText(_translate("Dialog", "Body Washing", None))
        self.Embalming.setText(_translate("Dialog", "Embalming", None))
        self.VIP.setText(_translate("Dialog", "VIP Services", None))
        self.Coffin.setText(_translate("Dialog", "Coffin Provision", None))
        self.Hearse.setText(_translate("Dialog", "Hearse Services", None))
        self.FlowerServices.setText(_translate("Dialog", "Flower Services", None))
        self.DeathCertificate.setText(_translate("Dialog", "Death Certificate", None))
        self.PostMortem.setText(_translate("Dialog", "Post Mortem", None))
        self.TextServices.setText(_translate("Dialog", "Tent Services", None))
        self.OtherServices.setText(_translate("Dialog", "Other Services", None))
        self.SubmitButton.setText(_translate("Dialog", "Submit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

